### ISSUE TITLE
dependency unavailable in R version 3.6.2

### ISSUE THREAD

**Issue by bvieth** [karakulahg/TEffectR#1]
Hello,

I tried to install your package but unfortunately the package biomartr is not available anymore (https://cran.r-project.org/web/packages/biomartr/index.html). 

Kind regards
Beate

**Comment by karakulahg** [comment]
Dear @bvieth ,

You are right that it seems like there is a problem while installing "biomartr" package from cran repository. Please Can you try to install the package from github by using "devtools" package that it is like that :

`library(devtools)` 
`install_github("HajkD/biomartr", build_vignettes = TRUE, dependencies = TRUE)`

Also you can try another ways for installing from [this link](https://www.rdocumentation.org/packages/biomartr/versions/0.0.3)

sincerely yours
@nzmye
