### ISSUE TITLE
Error in if (lmp(list) < 0.05) — part of writing results

### ISSUE THREAD

**Issue by Jenn996** [karakulahg/TEffectR#2]
Hi,

I'm running the program on aligned bams that were coordinate-sorted by STAR and indexed by samtools. Everything works except an error pops up when writing the results; the error is this:

Error in if (lmp(list) < 0.05) { : missing value where TRUE/FALSE needed

Do you have any insight into this? I think it may originate from the writingResultOfLM function, specifically in line 199 from your main.R file on here. Thanks!

**Comment by karakulahg** [comment]
Dear @Jenn996 ,

Sorry for the delay I noticed your issue much later and I noticed the error then solved the problem. thank you for your informing. The package works now. You can try it again.

Don't forget to reinstall the package. My suggestion is before do that you should uninstall the package. If you still get the error or not , please write a comment to us about it.  

Thank you,
sincerely,
@nzmye

**Comment by Jenn996** [comment]
Hi,
Thanks for getting back to me. Unfortunately, the error is still occurring. I did as you said and reinstalled TEffectR after uninstalling it. Is the updated package available or did I reinstall the same package?

**Comment by karakulahg** [comment]
Dear @Jenn996 ,

Yes it was updated. I checked and tested again the package but it works I didn't get any error. After you uninstall the package you should restart your R Session then Please make sure you reinstalled the package completely.  Also if you get same error, you can share me more information about the error. 

sincerely,
@nzmye
