### ISSUE TITLE
Incompatible with mouse assembly

### ISSUE THREAD

**Issue by juanb001** [karakulahg/TEffectR#3]
Hi,

Is there a reason the tool wasn't made compatible with mouse genome?

There seems to be an issue with the returnEnsembl function in biomart.R that accompanies TEffectR. Not sure if this was intentional, but if not, it would be appreciated if it was corrected.

Thanks!

**Comment by pebonte** [comment]
> Hi,
> 
> Is there a reason the tool wasn't made compatible with mouse genome?
> 
> There seems to be an issue with the returnEnsembl function in biomart.R that accompanies TEffectR. Not sure if this was intentional, but if not, it would be appreciated if it was corrected.
> 
> Thanks!

Hi,

Did you resolve the issue with the mouse assembly ? I have unfortunately the same problem...

**Comment by pebonte** [comment]
Hello, 
So I had the same problem as Juan and found the issue by removing the package and manually sourcing the R files from the GitHub. So basically there is a typo in 1 function so you can modify the R files and it will work (for me it did) :

```
returnEnsembl<-function(assembly,URL){
  if(assembly=="hg19" || assembly=="Grch37"){
    ensembl = biomaRt::useEnsembl(biomart="ensembl", dataset="hsapiens_gene_ensembl", GRCh = 37, host = URL, verbose = TRUE)
    return(ensembl)
  }else if(assembly=="hg38" || assembly=="Grch38"){
    ensembl = biomaRt::useEnsembl(biomart="ensembl", dataset="hsapiens_gene_ensembl", GRCh = 38, host = URL, verbose = TRUE)
    return(ensembl)
  }else if(y=="mm9" || y =="Grcm37"){
    ensembl = biomaRt::useEnsembl(biomart="ensembl", dataset="mmusculus_gene_ensembl",  host = URL, verbose = TRUE)
    return(ensembl)
  }else if(y=="mm10" || y =="Grcm38"){
    ensembl = biomaRt::useEnsembl(biomart="ensembl", dataset="mmusculus_gene_ensembl",  host = URL, verbose = TRUE)
    return(ensembl)
  }else{
    print("not found assembly")
    return(NULL)}
}
```

I replaced `y=="mm10" || y =="Grcm38"` by `assembly=="mm10" ||assembly =="Grcm38"`

Hopefully it will help someone.

Cheers,

Pierre-Emmanuel
